filebeat:
  inputs:
  - type: log
    enabled: true
    paths:
    - /var/log/kubernetes/audit/audit.log
    json.keys_under_root: true
    json.add_error_key: true
    multiline.pattern: '^\s'
    multiline.match: after
    fields:
      log_type: k8s-audit-logs
      index: k8s-audit-logs

output.logstash:
  hosts: ["elk-service:5044"]
