---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  template:
    metadata:
      labels:
        app: filebeat
      name: filebeat
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: filebeat
        image: komljen/filebeat
        resources:
          limits:
            cpu: 51m
            memory: 50Mi
        env:
        - name: LOGSTASH_HOSTS
          value: elk-service:5044
        - name: LOG_LEVEL
          value: debug
        - name: INDEX_PREFIX
          value: "K8S-%{[@metadata]}-%{+YYYY.MM.dd}"
        volumeMounts:
        - name: dinddockercontainers
          mountPath: /dind/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      volumes:
      - name: dinddockercontainers
        hostPath:
          path: /dind/docker/containers